### ISSUE TITLE
Loading errors paperspigot 1.19.3

### ISSUE THREAD

**Issue by TymekSL** [Mehran1022mm/Event-Core#2]
I have errors and plugin not loading. I have vault hooked with lighteco plugin

https://pastebin.com/7LcH0J8S

**Comment by Mehran1022mm** [comment]
Thanks for contacting me. I'll investigate this and let you know 😉

**Comment by Mehran1022mm** [comment]
I think that's a problem related to `plugin.yml`. To fix this (probably) do the steps blow:

1. Go to the plugins folder and find Event-Core-1.0.5.jar
2. Right-Click on it and select Open with WinRar or Open with ...
3. Double-Click and open the `plugin.yml`
4. Delete the 
```yml
libraries:
  - (i dont remember what i typed here)
```
5. Save the file and jar archive 
6. restart your server and let me know if this didn't helped you

**Comment by Mehran1022mm** [comment]
Or download the DEV version. [Click here](https://github.com/Mehran1022mm/Event-Core/suites/13888688217/artifacts/772288006)

**Comment by TymekSL** [comment]
> Or download the DEV version. [Click here](https://github.com/Mehran1022mm/Event-Core/suites/13888688217/artifacts/772288006)

[23:05:07 INFO]: [Event-Core] Enabling Event-Core v1.0.5
[23:05:07 INFO]: [Event-Core] Incompatible Version, Please Use 1.16.x And Above.
[23:05:07 INFO]: [Event-Core] Disabling Event-Core v1.0.5
[23:05:07 ERROR]: Error occurred while enabling Event-Core v1.0.5 (Is it up to date?)
java.lang.IllegalArgumentException: The embedded resource 'PlayersData.yml' cannot be found in plugins/Event-Core-1.0.5.jar
        at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:207) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at ir.Mehran1022.EventCore.Main.PlayersData(Main.java:89) ~[Event-Core-1.0.5.jar:?]
        at ir.Mehran1022.EventCore.Main.LoadThings(Main.java:75) ~[Event-Core-1.0.5.jar:?]
        at ir.Mehran1022.EventCore.Main.onEnable(Main.java:68) ~[Event-Core-1.0.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.3.jar:git-Paper-448]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:471) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Mehran1022mm** [comment]
I'll look into that. And I'll release a stable version after this. Sorry for the delay 😞

**Comment by TymekSL** [comment]
something news?

**Comment by Mehran1022mm** [comment]
Hi. Yes i fixed the bugs and issues but i want more time to checm the plugin and make it public

**Comment by TymekSL** [comment]
little long but have question when I change lobbby (test) server to 1.19.2 it will work>?

**Comment by Mehran1022mm** [comment]
Of course. Were supporting 1.14 - 1.20 currently.
About the update, i committed changes and plugin is ready to be released

**Comment by Mehran1022mm** [comment]
new pre-release is here download it from Releases

**Comment by TymekSL** [comment]
using spigot version dev (on the github there is .5) 
anyway: 
[23:23:22 INFO]: Leo693 issued server command: /event-core:event Start
[23:23:22 INFO]: EVENT » A Normal Event Has Been Started. Use "/Event Join" To Participate.
[23:23:22 INFO]: [Event-Core] Error When Trying To Send Message To Bungee
[23:23:22 WARN]: java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use EventCoreMessage)
[23:23:22 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:503)
[23:23:22 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.isOutgoingChannelRegistered(StandardMessenger.java:428)
[23:23:22 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:543)
[23:23:22 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.sendPluginMessage(CraftServer.java:2063)
[23:23:22 WARN]:        at Event-Core-1.0.6-DEV.jar//ir.Mehran1022.EventCore.Utils.Common.SendMessageToBungee(Common.java:107)
[23:23:22 WARN]:        at Event-Core-1.0.6-DEV.jar//ir.Mehran1022.EventCore.Commands.EventCommand.onCommand(EventCommand.java:203)
[23:23:22 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[23:23:22 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[23:23:22 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:911)
[23:23:22 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[23:23:22 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[23:23:22 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:316)
[23:23:22 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:300)
[23:23:22 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2288)
[23:23:22 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2248)
[23:23:22 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[23:23:22 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[23:23:22 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[23:23:22 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[23:23:22 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[23:23:22 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[23:23:22 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[23:23:22 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[23:23:22 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[23:23:22 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[23:23:22 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[23:23:22 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
[23:23:22 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
[23:23:22 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[23:23:22 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)


I saw: there is no bungee addon, 2 suggestions:
1. When there is no bungee addon make message "BUNGEE ADDON IS DISABLED" (or make it in config of plugin bungee-addon: true) 
2.   NoDescription: "&dA Normal Event Has Been Started. Use \"/Event Join\" To Participate."
  EventEnd: "&dEvent Has Been Ended. No One Can Join Now." 
this messages can make as: 

NoDescription: 
- "bla bla bla line1"
- "bla bla line 2"
- "i need multiline"
(because this is good look, with /n there is no good visibility)

**Comment by Mehran1022mm** [comment]
I'll look into that. Bungeecord addon is under development

**Comment by TymekSL** [comment]
2 months 0 updates ;((

**Comment by Mehran1022mm** [comment]
Sorry, i don't have enough time to develop my own plugins. I have work to do and im very busy. Maybe one day i do these things. I added the things you mentioned to the to-do list. I hope you understand

**Comment by TymekSL** [comment]
understand but all authors with future update said same thing "dont have time" xd always same

**Comment by Mehran1022mm** [comment]
you can't change the reality
