### ISSUE TITLE
Probably GUI issues 

### ISSUE THREAD

**Issue by TymekSL** [Mehran1022mm/Event-Core#3]
Have this errors 
(using dev version from spigot) 
https://pastebin.com/nD3nXygF

**Comment by Mehran1022mm** [comment]
i found the problem and its related to our gui system. ill fix that in next stable release. thanks for contacting us <3

**Comment by TymekSL** [comment]
Something news?

**Comment by TymekSL** [comment]
Still waiting...

**Comment by Mehran1022mm** [comment]
Bro im not gonna update it now im creating new plugins and this plugin is outdated and useless. I would make a bungeecord plugin if i want to remake this

**Comment by TymekSL** [comment]
LMAO 
. ill fix that in next stable release. thanks for contacting us
Decide!
I only waste time for waiting to stupid update. Yes I want still use this in bungee !!!

**Comment by Mehran1022mm** [comment]
Bro I have school and i don't want to waste my time writing stupid plugins that no one would use. If you want this go learn coding plugins and write one for yourself, god luck!

**Comment by TymekSL** [comment]
[00:20:02 ERROR]: Could not pass event InventoryClickEvent to Event-Core v1.0.6-DEV
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:209) ~[?:?]
        at ir.Mehran1022.EventCore.Listeners.InventoryClickListener.OnInvClick(InventoryClickListener.java:40) ~[Event-Core-1.0.6-DEV.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor296.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:git-Paper-17]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.jar:git-Paper-17]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.jar:git-Paper-17]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3197) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1425) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.jar:git-Paper-17]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by TymekSL** [comment]
> Bro I have school and i don't want to waste my time writing stupid plugins that no one would use. If you want this go learn coding plugins and write one for yourself, god luck!

thanks for wasting my time and waiting for nothing 4 months !

**Comment by TymekSL** [comment]
"nobody use this" 
Total Downloads: 256

**Comment by Mehran1022mm** [comment]
Can you provide what is your problem again?

**Comment by Mehran1022mm** [comment]
With error logs

**Comment by Mehran1022mm** [comment]
Sup dude. i fixed it now
